<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();

        DB::table('users')->truncate();
        DB::table('users')->insert([
            [
                'id' => '1',
                'name' => 'Administrator',
                'email' => 'admin@csa.com',
                'email_verified_at' => null,
                'password' => '$2y$12$oMTZhJVY.YTtE2ks4tVpvemSjIL9VBorJayjM5seBvMaUD.iS2csq',
                'remember_token' => null,
                'created_at' => '2026-05-23 12:37:30',
                'updated_at' => '2026-05-23 12:37:30',
            ],
        ]);

        DB::table('cms_contents')->truncate();
        DB::table('cms_contents')->insert([
            [
                'id' => '1',
                'key' => 'hero_badge',
                'section' => 'hero',
                'value' => 'PT. Cahaya Sentosa Abadi',
                'created_at' => '2026-05-23 07:38:55',
                'updated_at' => '2026-05-23 13:45:26',
            ],
            [
                'id' => '2',
                'key' => 'hero_title',
                'section' => 'hero',
                'value' => 'PRECISION METAL STAMPING',
                'created_at' => '2026-05-23 07:38:55',
                'updated_at' => '2026-05-23 07:38:55',
            ],
            [
                'id' => '3',
                'key' => 'hero_tagline',
                'section' => 'hero',
                'value' => 'SOLUTIONS FOR INDUSTRY',
                'created_at' => '2026-05-23 07:38:55',
                'updated_at' => '2026-05-23 07:38:55',
            ],
            [
                'id' => '4',
                'key' => 'hero_desc',
                'section' => 'hero',
                'value' => 'PT. Cahaya Sentosa Abadi adalah produsen komponen stamping logam presisi tinggi yang melayani industri otomotif, elektronik, dan manufaktur sejak tahun 2023. Berlokasi di Jl. Raya Curug - Kosambi, Cimahi, Kec. Klari, Karawang, Jawabarat',
                'created_at' => '2026-05-23 07:38:55',
                'updated_at' => '2026-05-24 14:12:31',
            ],
            [
                'id' => '5',
                'key' => 'hero_stats',
                'section' => 'hero',
                'value' => '[{"num":"2","unit":"+","label":"Year Experience"},{"num":"80","unit":"+","label":"Unit Press Machine"},{"num":"500","unit":"T","label":"Kapasitas Maks."},{"num":"0.1","unit":"%","label":"Defect Rate"},{"num":"200","unit":"+","label":"Klien Aktif"},{"num":"±0.05","unit":"mm","label":"Toleransi Presisi"}]',
                'created_at' => '2026-05-23 07:38:55',
                'updated_at' => '2026-05-24 16:20:00',
            ],
            [
                'id' => '7',
                'key' => 'ticker_items',
                'section' => 'ticker',
                'value' => '["Progressive Die Stamping","Transfer Die Stamping","Deep Drawing","Fine Blanking","Tool & Die Making","Roll Forming","Compound Die Stamping","Surface Treatment"]',
                'created_at' => '2026-05-23 07:38:55',
                'updated_at' => '2026-05-23 07:38:55',
            ],
            [
                'id' => '8',
                'key' => 'about_title',
                'section' => 'about',
                'value' => 'Experience 10 Years',
                'created_at' => '2026-05-23 07:38:55',
                'updated_at' => '2026-05-23 13:06:26',
            ],
            [
                'id' => '9',
                'key' => 'about_desc_1',
                'section' => 'about',
                'value' => 'PT. Cahaya Sentosa Abadi didirikan pada tahun 2023 sebagai perusahaan manufaktur komponen stamping logam di kawasan industri Cikarang, Jawa Barat. Selama lebih dari dua dekade, kami telah berkembang menjadi salah satu mitra stamping terpercaya bagi perusahaan-perusahaan multinasional di Indonesia.',
                'created_at' => '2026-05-23 07:38:55',
                'updated_at' => '2026-05-24 14:11:44',
            ],
            [
                'id' => '10',
                'key' => 'about_desc_2',
                'section' => 'about',
                'value' => 'Dengan lebih dari 500 karyawan terlatih dan fasilitas produksi seluas 35.000 m², kami mampu memenuhi kebutuhan komponen presisi dalam volume besar dengan konsistensi kualitas tinggi dan tepat waktu.',
                'created_at' => '2026-05-23 07:38:55',
                'updated_at' => '2026-05-23 07:38:55',
            ],
            [
                'id' => '11',
                'key' => 'about_highlights',
                'section' => 'about',
                'value' => '[{"title":"Lokasi Strategis","desc":"Jl. Raya Curug - Kosambi, Cimahi, Kec. Klari, Karawang, Jawabarat","icon":"ti-map-pin"},{"title":"500+ Karyawan Terlatih","desc":"Teknisi, engineer, dan QC berpengalaman","icon":"ti-users"},{"title":"Fasilitas 35.000 m²","desc":"Area produksi, tool room, gudang, dan QC lab","icon":"ti-building-factory-2"}]',
                'created_at' => '2026-05-23 07:38:55',
                'updated_at' => '2026-05-23 13:24:32',
            ],
            [
                'id' => '12',
                'key' => 'about_visi',
                'section' => 'about',
                'value' => 'Menjadi perusahaan stamping logam terkemuka di Asia Tenggara yang dikenal atas presisi, keandalan, dan inovasi dalam setiap komponen yang kami produksi.',
                'created_at' => '2026-05-23 07:38:55',
                'updated_at' => '2026-05-23 07:38:55',
            ],
            [
                'id' => '13',
                'key' => 'about_misi',
                'section' => 'about',
                'value' => '["Menghasilkan komponen stamping berkualitas tinggi dengan toleransi presisi sesuai standar industri","Menerapkan sistem manajemen mutu IATF 16949 secara konsisten","Mengembangkan sumber daya manusia yang kompeten dan berkarakter","Memberikan layanan terbaik kepada pelanggan dengan pengiriman tepat waktu","Menjalankan operasional yang ramah lingkungan sesuai ISO 14001","1"]',
                'created_at' => '2026-05-23 07:38:55',
                'updated_at' => '2026-05-23 13:22:45',
            ],
            [
                'id' => '14',
                'key' => 'products_eyebrow',
                'section' => 'products',
                'value' => 'SERVICE & PRODUCT',
                'created_at' => '2026-05-23 07:38:55',
                'updated_at' => '2026-05-23 13:16:00',
            ],
            [
                'id' => '15',
                'key' => 'products_title',
                'section' => 'products',
                'value' => 'Our Stamping Capabilities',
                'created_at' => '2026-05-23 07:38:55',
                'updated_at' => '2026-05-23 13:15:31',
            ],
            [
                'id' => '16',
                'key' => 'products_sub',
                'section' => 'products',
                'value' => 'We provide complete stamping solutions, from die design to mass production.',
                'created_at' => '2026-05-23 07:38:55',
                'updated_at' => '2026-05-23 13:15:31',
            ],
            [
                'id' => '17',
                'key' => 'machines_eyebrow',
                'section' => 'machines',
                'value' => 'Manufacturing Facilities',
                'created_at' => '2026-05-23 07:38:55',
                'updated_at' => '2026-05-24 14:20:24',
            ],
            [
                'id' => '18',
                'key' => 'machines_title',
                'section' => 'machines',
                'value' => 'Machinery & Equipment',
                'created_at' => '2026-05-23 07:38:55',
                'updated_at' => '2026-05-24 14:20:24',
            ],
            [
                'id' => '19',
                'key' => 'machines_sub',
                'section' => 'machines',
                'value' => 'Equipped with modern press machines in various capacities to meet your production needs.',
                'created_at' => '2026-05-23 07:38:55',
                'updated_at' => '2026-05-24 14:20:24',
            ],
            [
                'id' => '20',
                'key' => 'machines_facilities',
                'section' => 'machines',
                'value' => '[{"name":"CMM Room","desc":"Coordinate measuring machine","icon":"ti-microscope"},{"name":"3D Scanner","desc":"Reverse engineering & inspection","icon":"ti-scan"},{"name":"Heat Treatment","desc":"Hardening & tempering","icon":"ti-temperature"},{"name":"Automated WH","desc":"Automated warehouse system","icon":"ti-package"}]',
                'created_at' => '2026-05-23 07:38:55',
                'updated_at' => '2026-05-23 07:38:55',
            ],
            [
                'id' => '21',
                'key' => 'quality_eyebrow',
                'section' => 'quality',
                'value' => 'Quality',
                'created_at' => '2026-05-23 07:38:55',
                'updated_at' => '2026-05-24 08:53:46',
            ],
            [
                'id' => '22',
                'key' => 'quality_title',
                'section' => 'quality',
                'value' => 'Highest Quality Standards',
                'created_at' => '2026-05-23 07:38:55',
                'updated_at' => '2026-05-24 16:09:01',
            ],
            [
                'id' => '23',
                'key' => 'quality_sub',
                'section' => 'quality',
                'value' => 'We are committed to measurable and consistent quality at every stage of the production process.',
                'created_at' => '2026-05-23 07:38:55',
                'updated_at' => '2026-05-24 16:09:01',
            ],
            [
                'id' => '25',
                'key' => 'quality_steps',
                'section' => 'quality',
                'value' => '[{"num":"01","title":"Incoming Material Inspection","desc":"Inspeksi material bahan baku menggunakan spectrometer dan hardness tester sebelum masuk produksi."},{"num":"02","title":"In-Process Quality Check","desc":"Pemeriksaan dimensi secara berkala selama proses produksi berlangsung menggunakan SPC."},{"num":"03","title":"Final Inspection","desc":"Inspeksi akhir menggunakan CMM dan 3D scanner untuk memastikan setiap komponen sesuai drawing."},{"num":"04","title":"Traceability & Documentation","desc":"Setiap lot produksi terdokumentasi lengkap dengan nomor batch dan hasil inspeksi untuk traceability penuh."}]',
                'created_at' => '2026-05-23 07:38:55',
                'updated_at' => '2026-05-23 07:38:55',
            ],
            [
                'id' => '26',
                'key' => 'clients_eyebrow',
                'section' => 'clients',
                'value' => 'KLIEN & MITRA',
                'created_at' => '2026-05-23 07:38:55',
                'updated_at' => '2026-05-23 07:38:55',
            ],
            [
                'id' => '27',
                'key' => 'clients_title',
                'section' => 'clients',
                'value' => 'Dipercaya Oleh Perusahaan Terkemuka',
                'created_at' => '2026-05-23 07:38:55',
                'updated_at' => '2026-05-23 07:38:55',
            ],
            [
                'id' => '28',
                'key' => 'clients_intro',
                'section' => 'clients',
                'value' => 'Selama lebih dari 26 tahun, kami telah menjadi mitra terpercaya bagi perusahaan-perusahaan multinasional di berbagai sektor industri di Indonesia dan kawasan Asia Tenggara.',
                'created_at' => '2026-05-23 07:38:55',
                'updated_at' => '2026-05-23 07:38:55',
            ],
            [
                'id' => '29',
                'key' => 'testimonial_quote',
                'section' => 'clients',
                'value' => 'PT. Cahaya Sentosa Abadi telah menjadi mitra stamping kami selama lebih dari 10 tahun. Kualitas komponen yang konsisten, pengiriman tepat waktu, dan responsivitas tim mereka terhadap perubahan spesifikasi menjadikan mereka mitra yang sangat kami andalkan.',
                'created_at' => '2026-05-23 07:38:55',
                'updated_at' => '2026-05-23 07:38:55',
            ],
            [
                'id' => '30',
                'key' => 'testimonial_author',
                'section' => 'clients',
                'value' => 'Budi Santoso',
                'created_at' => '2026-05-23 07:38:55',
                'updated_at' => '2026-05-23 07:38:55',
            ],
            [
                'id' => '31',
                'key' => 'testimonial_role',
                'section' => 'clients',
                'value' => 'Procurement Manager, PT Astra Honda Motor',
                'created_at' => '2026-05-23 07:38:56',
                'updated_at' => '2026-05-23 07:38:56',
            ],
            [
                'id' => '32',
                'key' => 'contact_eyebrow',
                'section' => 'contact',
                'value' => 'KONTAK',
                'created_at' => '2026-05-23 07:38:56',
                'updated_at' => '2026-05-23 07:38:56',
            ],
            [
                'id' => '33',
                'key' => 'contact_title',
                'section' => 'contact',
                'value' => 'Hubungi Kami',
                'created_at' => '2026-05-23 07:38:56',
                'updated_at' => '2026-05-23 07:38:56',
            ],
            [
                'id' => '34',
                'key' => 'contact_sub',
                'section' => 'contact',
                'value' => 'Tim kami siap membantu kebutuhan stamping Anda. Kirimkan pertanyaan atau request quotation.',
                'created_at' => '2026-05-23 07:38:56',
                'updated_at' => '2026-05-23 07:38:56',
            ],
            [
                'id' => '35',
                'key' => 'contact_alamat',
                'section' => 'contact',
                'value' => 'Jl. Raya Curug - Kosambi, Cimahi, Kec. Klari, Karawang,',
                'created_at' => '2026-05-23 07:38:56',
                'updated_at' => '2026-05-23 13:16:57',
            ],
            [
                'id' => '36',
                'key' => 'contact_alamat_sub',
                'section' => 'contact',
                'value' => 'Jawa Barat 41371',
                'created_at' => '2026-05-23 07:38:56',
                'updated_at' => '2026-05-23 13:16:57',
            ],
            [
                'id' => '37',
                'key' => 'contact_telp',
                'section' => 'contact',
                'value' => '+62 21 8990 1234',
                'created_at' => '2026-05-23 07:38:56',
                'updated_at' => '2026-05-23 07:38:56',
            ],
            [
                'id' => '38',
                'key' => 'contact_fax',
                'section' => 'contact',
                'value' => '+62 21 8990 1235 (Fax)',
                'created_at' => '2026-05-23 07:38:56',
                'updated_at' => '2026-05-23 07:38:56',
            ],
            [
                'id' => '39',
                'key' => 'contact_email_1',
                'section' => 'contact',
                'value' => 'marketing@cahayasentosa.co.id',
                'created_at' => '2026-05-23 07:38:56',
                'updated_at' => '2026-05-23 07:38:56',
            ],
            [
                'id' => '40',
                'key' => 'contact_email_2',
                'section' => 'contact',
                'value' => 'info@cahayasentosa.co.id',
                'created_at' => '2026-05-23 07:38:56',
                'updated_at' => '2026-05-23 07:38:56',
            ],
            [
                'id' => '41',
                'key' => 'contact_jam_1',
                'section' => 'contact',
                'value' => 'Senin — Jumat: 08.00 — 17.00',
                'created_at' => '2026-05-23 07:38:56',
                'updated_at' => '2026-05-23 07:38:56',
            ],
            [
                'id' => '42',
                'key' => 'contact_jam_2',
                'section' => 'contact',
                'value' => 'Sabtu: 08.00 — 13.00 WIB',
                'created_at' => '2026-05-23 07:38:56',
                'updated_at' => '2026-05-23 07:38:56',
            ],
            [
                'id' => '43',
                'key' => 'company_certs',
                'section' => 'profile',
                'value' => '[{"name":"ISO40001","desc":"Certifiakat Kualitas Mutu","icon":"ti-shield"}]',
                'created_at' => '2026-05-23 14:01:14',
                'updated_at' => '2026-05-23 14:05:28',
            ],
            [
                'id' => '44',
                'key' => 'hero_certs',
                'section' => null,
                'value' => '["ISO 9001:2015","IATF 16949","ISO 14001","5S & Kaizen"]',
                'created_at' => '2026-05-23 14:02:33',
                'updated_at' => '2026-05-23 14:02:33',
            ],
            [
                'id' => '45',
                'key' => 'quality_certs',
                'section' => null,
                'value' => '[{"name":"ISO 9001:2015","desc":"Sistem manajemen kualitas untuk konsistensi produk dan kepuasan pelanggan","icon":"ti-certificate"},{"name":"IATF 16949","desc":"Standar kualitas internasional khusus industri otomotif","icon":"ti-car"},{"name":"ISO 14001","desc":"Sistem manajemen lingkungan untuk operasional yang berkelanjutan","icon":"ti-leaf"},{"name":"5S & Kaizen","desc":"Penerapan lean manufacturing untuk efisiensi dan perbaikan berkelanjutan","icon":"ti-award"}]',
                'created_at' => '2026-05-23 14:02:33',
                'updated_at' => '2026-05-23 14:02:33',
            ],
            [
                'id' => '46',
                'key' => 'footer_certs',
                'section' => null,
                'value' => '[]',
                'created_at' => '2026-05-24 13:57:02',
                'updated_at' => '2026-05-24 13:57:02',
            ],
            [
                'id' => '47',
                'key' => 'footer_services',
                'section' => null,
                'value' => '[]',
                'created_at' => '2026-05-24 13:57:02',
                'updated_at' => '2026-05-24 13:57:02',
            ],
            [
                'id' => '48',
                'key' => 'footer_copyright',
                'section' => null,
                'value' => null,
                'created_at' => '2026-05-24 13:57:02',
                'updated_at' => '2026-05-24 14:00:03',
            ],
            [
                'id' => '49',
                'key' => 'footer_subcopy',
                'section' => null,
                'value' => 'Precision Metal Stamping',
                'created_at' => '2026-05-24 13:57:02',
                'updated_at' => '2026-05-24 13:57:02',
            ],
            [
                'id' => '50',
                'key' => 'footer_brand_name',
                'section' => null,
                'value' => 'PT. Cahaya Sentosa Abadi',
                'created_at' => '2026-05-24 14:04:25',
                'updated_at' => '2026-05-24 14:04:25',
            ],
            [
                'id' => '51',
                'key' => 'footer_tagline',
                'section' => null,
                'value' => 'Produsen komponen stamping logam presisi untuk industri otomotif, elektronik, dan manufaktur. Berkomitmen pada kualitas dan ketepatan waktu sejak 2023',
                'created_at' => '2026-05-24 14:04:25',
                'updated_at' => '2026-05-24 14:04:25',
            ],
            [
                'id' => '52',
                'key' => 'contact_map_embed',
                'section' => null,
                'value' => 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3964.8686693753207!2d107.37377147499197!3d-6.4109129935798785!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e69749b3b796af7%3A0xda7b73f9ff4e5254!2sPT%20Cahaya%20Sentosa%20Abadi!5e0!3m2!1sid!2sid!4v1779633026712!5m2!1sid!2sid" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade',
                'created_at' => '2026-05-24 14:30:39',
                'updated_at' => '2026-05-24 14:31:23',
            ],
            [
                'id' => '53',
                'key' => 'social_wa',
                'section' => null,
                'value' => '6281234567890',
                'created_at' => '2026-05-24 14:35:42',
                'updated_at' => '2026-05-24 14:35:42',
            ],
            [
                'id' => '54',
                'key' => 'social_tiktok',
                'section' => null,
                'value' => 'https://tiktok.com/@cahaya_sentosa',
                'created_at' => '2026-05-24 14:37:13',
                'updated_at' => '2026-05-24 14:37:13',
            ],
            [
                'id' => '55',
                'key' => 'social_ig',
                'section' => null,
                'value' => 'https://instagram.com/cahaya_sentosa',
                'created_at' => '2026-05-24 14:37:13',
                'updated_at' => '2026-05-24 14:37:13',
            ],
            [
                'id' => '56',
                'key' => 'social_fb',
                'section' => null,
                'value' => 'https://facebook.com/cahaya_sentosa',
                'created_at' => '2026-05-24 14:37:13',
                'updated_at' => '2026-05-24 14:37:13',
            ],
        ]);

        DB::table('products')->truncate();
        DB::table('products')->insert([
            [
                'id' => '1',
                'tag' => 'HIGH VOLUME',
                'name' => 'Progressive Stamping',
                'desc' => 'Proses stamping berkelanjutan dengan beberapa stasiun die untuk produksi volume tinggi secara efisien.',
                'specs' => '["±0.05mm toleransi", "Vol. tinggi", "Otomatis"]',
                'icon' => 'ti-adjustments-horizontal',
                'img' => null,
                'tolerance' => '±0.05 mm (High Precision)',
                'capacity' => '45 Ton — 300 Ton',
                'speed' => '45 — 120 strokes / m',
                'volume' => 'High Volume Mass',
                'auxiliary' => 'Peralatan decoiler loops otomatis, roller straightener leveling loops, pelumas otomatis mikro spray.',
                'safety' => 'Tirai cahaya optoelektronik keselamatan kerja, sensor deteksi penumpukan pelat ganda, rem kopling pneumatik darurat.',
                'typical' => 'Terminal kelistrikan kuningan, klip pegas motor, braket mesin mobil, EMI shielding electronics housing.',
                'created_at' => '2026-05-23 07:38:55',
                'updated_at' => '2026-05-23 07:38:55',
            ],
            [
                'id' => '2',
                'tag' => 'COMPLEX SHAPE',
                'name' => 'Deep Drawing',
                'desc' => 'Proses pembentukan lembaran logam menjadi komponen berbentuk cup, silinder, atau shell tanpa sambungan.',
                'specs' => '["Tanpa sambungan", "Ketebalan seragam"]',
                'icon' => 'ti-arrow-down-circle',
                'img' => null,
                'tolerance' => '±0.10 mm (Deep drawing flow)',
                'capacity' => '100 Ton — 500 Ton',
                'speed' => '15 — 35 strokes / m',
                'volume' => 'Medium to High Parts',
                'auxiliary' => 'Bantalan hidrolik kontrol tekanan, pengontrol ketebalan lembaran, sistem pembentuk tanpa sambungan khusus.',
                'safety' => 'Tirai cahaya optoelektronik keselamatan kerja, sensor deteksi penumpukan pelat ganda, rem kopling pneumatik darurat.',
                'typical' => 'Baterai EV shell cups, filter oli silinder tanpa sambungan, tabung pemadam api, tutup tangki BBM.',
                'created_at' => '2026-05-23 07:38:55',
                'updated_at' => '2026-05-23 07:38:55',
            ],
            [
                'id' => '3',
                'tag' => 'PRECISION CUT',
                'name' => 'Fine Blanking',
                'desc' => 'Pemotongan presisi dengan permukaan shear yang halus dan rata tanpa memerlukan proses finishing tambahan.',
                'specs' => '["Permukaan halus", "No finishing"]',
                'icon' => 'ti-scissors',
                'img' => null,
                'tolerance' => '±0.01 mm (Micro fine clearance)',
                'capacity' => '80 Ton — 250 Ton',
                'speed' => '60 — 180 strokes / m',
                'volume' => 'Safety-Critical Precision',
                'auxiliary' => 'Penjepit pilot mikro hidrolik presisi tinggi, fine blanking punch clearances, die ejector pad assemblies.',
                'safety' => 'Tirai cahaya optoelektronik keselamatan kerja, sensor deteksi penumpukan pelat ganda, rem kopling pneumatik darurat.',
                'typical' => 'Roda gigi transmisi presisi halus, kopling cakram, pelat katup pengereman safety, spacer mesin mikro.',
                'created_at' => '2026-05-23 07:38:55',
                'updated_at' => '2026-05-23 07:38:55',
            ],
            [
                'id' => '4',
                'tag' => 'MULTI-STEP',
                'name' => 'Transfer Stamping',
                'desc' => 'Proses multi-tahap dengan transfer otomatis antar stasiun, ideal untuk komponen berukuran besar dan kompleks.',
                'specs' => '["Komponen besar", "Transfer otomatis"]',
                'icon' => 'ti-repeat',
                'img' => null,
                'tolerance' => '±0.15 mm (Transfer layout spec)',
                'capacity' => '200 Ton — 500 Ton',
                'speed' => '12 — 30 strokes / m',
                'volume' => 'Large Frame Structural',
                'auxiliary' => 'Robot manipulator lengan transfer otomatis, stasiun pengubah die cepat, pilot indexing pins.',
                'safety' => 'Tirai cahaya optoelektronik keselamatan kerja, sensor deteksi penumpukan pelat ganda, rem kopling pneumatik darurat.',
                'typical' => 'Braket penguat sasis otomotif ukuran besar, panel pintu struktural, penutup kompresor pendingin udara.',
                'created_at' => '2026-05-23 07:38:55',
                'updated_at' => '2026-05-23 07:38:55',
            ],
            [
                'id' => '5',
                'tag' => 'IN-HOUSE',
                'name' => 'Tool & Die Making',
                'desc' => 'Desain dan fabrikasi die in-house menggunakan CAD/CAM dan mesin CNC presisi tinggi untuk semua jenis tooling.',
                'specs' => '["CAD/CAM", "CNC Machining"]',
                'icon' => 'ti-tool',
                'img' => null,
                'tolerance' => '±0.002 mm (CNC Tooling precision)',
                'capacity' => 'CNC travel clearance',
                'speed' => 'Up to 24,000 RPM Spindle',
                'volume' => 'Custom Prototype & Die',
                'auxiliary' => 'Sistem CAD/CAM die design modeling, wire cut EDM generator sub-micron, multi-axis CNC stage fixtures.',
                'safety' => 'Pintu kabin tertutup sensor interlock laser, sensor pendeteksi getaran poros spindel spindel, sensor overload motor CNC.',
                'typical' => 'Pembuatan progressive dies set, stage tooling dies, transfer die arm fixtures, CNC custom molds presisi.',
                'created_at' => '2026-05-23 07:38:55',
                'updated_at' => '2026-05-23 07:38:55',
            ],
            [
                'id' => '6',
                'tag' => 'FINISHING',
                'name' => 'Surface Treatment',
                'desc' => 'Layanan electroplating, powder coating, dan phosphating untuk meningkatkan ketahanan korosi dan estetika produk.',
                'specs' => '["Electroplating", "Powder Coating"]',
                'icon' => 'ti-droplets',
                'img' => null,
                'tolerance' => 'AS9100 / ASTM coating rating',
                'capacity' => 'Electroplating conveyorized',
                'speed' => 'Realtime Continuous Line',
                'volume' => 'Outbound Finished Coating',
                'auxiliary' => 'Bak pelapis electroplating kimia otomatis, oven conveyorized powder coating, spray pretreatment loops.',
                'safety' => 'Pembersih udara filter hisap uap kimia asam, pengaman katup pelepas gas otomatis, sensor kebocoran kimia.',
                'typical' => 'Pelapisan anti-karat komponen sasis, powder coating casing elektronik, zinc plating terminal tembaga.',
                'created_at' => '2026-05-23 07:38:55',
                'updated_at' => '2026-05-23 07:38:55',
            ],
            [
                'id' => '7',
                'tag' => 'TES',
                'name' => 'TES',
                'desc' => 'TES',
                'specs' => '[]',
                'icon' => 'ti-settings-2',
                'img' => '/uploads/products/6a11a69e08175.webp',
                'tolerance' => 'TES',
                'capacity' => 'TES',
                'speed' => 'TES',
                'volume' => 'TES',
                'auxiliary' => 'TES',
                'safety' => 'TES',
                'typical' => 'TES',
                'created_at' => '2026-05-23 12:58:10',
                'updated_at' => '2026-05-23 15:47:38',
            ],
        ]);

        DB::table('machines')->truncate();
        DB::table('machines')->insert([
            [
                'id' => '1',
                'name' => 'Mechanical Press',
                'spec' => 'Kapasitas 30T — 300T',
                'qty' => '24',
                'icon' => 'ti-settings-2',
                'img' => '/uploads/machines/6a12bd9cd8f19.webp',
                'longDesc' => 'Armada mesin press mekanikal kami merupakan tulang punggung produksi massal dengan kecepatan ketukan tinggi. Dilengkapi dengan unit otomatisasi rol koil pengumpan (feeder lines) untuk mendukung efisiensi pengerjaan tinggi.',
                'origin' => 'Jepang / Taiwan (AIDA, Seyi)',
                'precision' => 'JIS B 6402 Grade 1 Accuracy',
                'safety' => 'Dual-valve pneumatic clutch & optoelectronic light curtains keselamatan kerja otomatis, interlock overload sensors.',
                'application' => 'Braket otomotif, terminal kuningan kelistrikan, klip logam otomotif, EMI shielding electronics housing.',
                'created_at' => '2026-05-23 07:38:55',
                'updated_at' => '2026-05-24 08:58:04',
            ],
            [
                'id' => '2',
                'name' => 'Hydraulic Press',
                'spec' => 'Kapasitas 100T — 500T',
                'qty' => '12',
                'icon' => 'ti-droplet-half-2',
                'img' => '/uploads/machines/6a12bdbe1ddb4.webp',
                'longDesc' => 'Didesain untuk proses pengerjaan penarikan dalam (deep drawing) yang membutuhkan tekanan stabil sepanjang stroke. Mampu menangani lembaran logam tebal menjadi bentuk silinder atau cup tanpa sambungan.',
                'origin' => 'Jepang / Taiwan (AMADA, Seyi)',
                'precision' => 'JIS B 6403 Hydraulic Standard',
                'safety' => 'Hydraulic overload protector valves, emergency physical interlock gate sensor, rem kopling darurat pneumatik.',
                'application' => 'EV battery case shells, filter oli silinder, tabung pemadam api tanpa sambungan, tutup tangki bahan bakar.',
                'created_at' => '2026-05-23 07:38:55',
                'updated_at' => '2026-05-24 08:58:38',
            ],
            [
                'id' => '3',
                'name' => 'Servo Press',
                'spec' => 'Kapasitas 80T — 200T',
                'qty' => '8',
                'icon' => 'ti-cpu',
                'img' => null,
                'longDesc' => 'Menggunakan teknologi motor AC servo dengan kurva ketukan yang dapat diprogram penuh. Memberikan akurasi penekanan mikro-milimeter guna menghindari keretakan material (springback control) pada material berkekuatan tarik tinggi.',
                'origin' => 'Jepang (AIDA, AMADA)',
                'precision' => 'Micron-level control (±0.005mm)',
                'safety' => 'Direct torque motor feedback sensor, emergency brake switch, sensor pendeteksi ketebalan plat ganda.',
                'application' => 'Komponen safety-critical otomotif, roda gigi transmisi mikro presisi halus, kopling cakram, spacer mesin.',
                'created_at' => '2026-05-23 07:38:55',
                'updated_at' => '2026-05-23 07:38:55',
            ],
            [
                'id' => '4',
                'name' => 'Transfer Press',
                'spec' => 'Kapasitas 200T — 500T',
                'qty' => '6',
                'icon' => 'ti-box',
                'img' => null,
                'longDesc' => 'Menghubungkan beberapa proses dies (blanking, bending, piercing) dalam satu rangkaian stasiun otomatis dengan robot lengan transfer. Ideal untuk memproduksi komponen struktural berukuran menengah hingga besar secara massal.',
                'origin' => 'Jepang (Komatsu)',
                'precision' => 'Automated stational alignment accuracy',
                'safety' => 'Pneumatic transfer feedback lines, physical perimeter fencing, tirai cahaya optoelektronik keselamatan kerja.',
                'application' => 'Sasis struktural otomotif ukuran besar, kompresor AC shells, panel pintu struktural, komponen frame.',
                'created_at' => '2026-05-23 07:38:55',
                'updated_at' => '2026-05-23 07:38:55',
            ],
            [
                'id' => '5',
                'name' => 'CNC Machining Center',
                'spec' => 'Tool room & die making',
                'qty' => '14',
                'icon' => 'ti-sparkles',
                'img' => null,
                'longDesc' => 'Fasilitas in-house tooling kami dilengkapi dengan CNC millings berkecepatan tinggi untuk membuat, memodifikasi, dan merawat cetakan dies logam secara presisi, menjamin kesiapan cetakan tanpa bergantung vendor luar.',
                'origin' => 'Jepang / Taiwan (Matsuura, YCM)',
                'precision' => 'Sub-micron tooling tolerance (±0.002mm)',
                'safety' => 'Enclosed cabin interlock door, automated spindle overload monitor, dust filtration suction loops.',
                'application' => 'Pembuatan progressive dies set, stage tooling dies, transfer die arm fixtures, CNC custom molds presisi.',
                'created_at' => '2026-05-23 07:38:55',
                'updated_at' => '2026-05-23 07:38:55',
            ],
            [
                'id' => '6',
                'name' => 'Welding Robot',
                'spec' => 'Spot & MIG Welding',
                'qty' => '10',
                'icon' => 'ti-robot',
                'img' => null,
                'longDesc' => 'Lengan robot multi-axis otomatis untuk pengelasan titik (spot welding) dan pengelasan gas metal (MIG). Menghasilkan pengelasan yang rapi, penetrasi kuat, dan bebas dari cacat las manusia pada komponen rakitan.',
                'origin' => 'Jepang (OTC Daihen, Yaskawa)',
                'precision' => 'High repeatability path accuracy (±0.08mm)',
                'safety' => 'Flash arc safety curtain, area laser safety scanners, physical fencing perimeter interlock.',
                'application' => 'Sub-assembly welding bracket otomotif, reinforcement panel sasis, pengelasan presisi sasis.',
                'created_at' => '2026-05-23 07:38:55',
                'updated_at' => '2026-05-23 07:38:55',
            ],
            [
                'id' => '7',
                'name' => 'KOMATSU',
                'spec' => '500 TON',
                'qty' => '12',
                'icon' => 'ti-settings-2',
                'img' => '/uploads/machines/GzyVVSioOVABFLG8Uwua9NlMqWIYGC5HtK02dpXP.jpg',
                'longDesc' => 'TESS',
                'origin' => 'JEPANG',
                'precision' => 'TEASD',
                'safety' => 'ADSAD',
                'application' => 'ADAS',
                'created_at' => '2026-05-23 12:52:27',
                'updated_at' => '2026-05-24 08:55:58',
            ],
        ]);

        DB::table('facilities')->truncate();
        DB::table('facilities')->insert([
            [
                'id' => '1',
                'name' => 'Area Produksi',
                'short_desc' => 'Area stamping dan assembling utama dengan tata letak optimal.',
                'long_desc' => 'Area produksi berstandar industri 5S dengan pembagian zona kerja yang jelas untuk memaksimalkan keselamatan dan efisiensi alur material.',
                'icon' => 'ti-settings-2',
                'img' => '/uploads/facilities/6a12c989d010e.webp',
                'spec' => '[{"label":"Kapasitas Layout","value":"Terintegrasi"},{"label":"Luas Area","value":"Terukur"}]',
                'created_at' => '2026-05-24 09:24:54',
                'updated_at' => '2026-05-24 09:48:57',
            ],
            [
                'id' => '2',
                'name' => 'Tool Room',
                'short_desc' => 'Perawatan, perbaikan, dan modifikasi dies (cetakan) secara mandiri.',
                'long_desc' => 'Dilengkapi fasilitas CNC Machining Center mandiri untuk menjamin kecepatan perbaikan dan perawatan cetakan dies tanpa pihak ketiga.',
                'icon' => 'ti-tool',
                'img' => '/uploads/facilities/6a12c96469235.webp',
                'spec' => '[{"label":"Standard","value":"JIS/ISO"},{"label":"Equipment","value":"CNC, EDM"}]',
                'created_at' => '2026-05-24 09:24:54',
                'updated_at' => '2026-05-24 09:48:20',
            ],
            [
                'id' => '3',
                'name' => 'Gudang',
                'short_desc' => 'Penyimpanan bahan baku dan barang jadi dengan manajemen inventory yang baik.',
                'long_desc' => 'Sistem penyimpanan dan manajemen inventaris berbasis rak terstruktur dengan sistem FIFO (First In First Out) untuk menjamin kualitas material.',
                'icon' => 'ti-package',
                'img' => '/uploads/facilities/6a12c99382f28.webp',
                'spec' => '[{"label":"Sistem","value":"Terkomputerisasi"},{"label":"Alur","value":"FIFO"}]',
                'created_at' => '2026-05-24 09:24:54',
                'updated_at' => '2026-05-24 09:49:07',
            ],
            [
                'id' => '4',
                'name' => 'QC Lab',
                'short_desc' => 'Laboratorium jaminan mutu dengan alat ukur presisi tinggi (CMM).',
                'long_desc' => 'Laboratorium isolasi bersuhu terkontrol untuk proses pengukuran mikroskopis menggunakan alat CMM (Coordinate Measuring Machine) dan Hardness Tester.',
                'icon' => 'ti-microscope',
                'img' => '/uploads/facilities/6a12c970a20b1.webp',
                'spec' => '[{"label":"Suhu Terkontrol","value":"Ya"},{"label":"Alat","value":"CMM, Profile Projector"}]',
                'created_at' => '2026-05-24 09:24:54',
                'updated_at' => '2026-05-24 09:48:32',
            ],
        ]);

        DB::table('clients')->truncate();
        DB::table('clients')->insert([
            [
                'id' => '1',
                'name' => 'Toyota',
                'industry' => 'Otomotif',
                'logo_path' => null,
                'created_at' => '2026-05-23 07:38:56',
                'updated_at' => '2026-05-23 07:38:56',
            ],
            [
                'id' => '2',
                'name' => 'Astra Honda',
                'industry' => 'Otomotif',
                'logo_path' => null,
                'created_at' => '2026-05-23 07:38:56',
                'updated_at' => '2026-05-23 07:38:56',
            ],
            [
                'id' => '3',
                'name' => 'Denso',
                'industry' => 'Komponen Otomotif',
                'logo_path' => null,
                'created_at' => '2026-05-23 07:38:56',
                'updated_at' => '2026-05-23 07:38:56',
            ],
            [
                'id' => '4',
                'name' => 'Yamaha',
                'industry' => 'Otomotif',
                'logo_path' => null,
                'created_at' => '2026-05-23 07:38:56',
                'updated_at' => '2026-05-23 07:38:56',
            ],
            [
                'id' => '5',
                'name' => 'Panasonic',
                'industry' => 'Elektronik',
                'logo_path' => null,
                'created_at' => '2026-05-23 07:38:56',
                'updated_at' => '2026-05-23 07:38:56',
            ],
            [
                'id' => '6',
                'name' => 'Samsung SDI',
                'industry' => 'Baterai EV',
                'logo_path' => null,
                'created_at' => '2026-05-23 07:38:56',
                'updated_at' => '2026-05-23 07:38:56',
            ],
            [
                'id' => '7',
                'name' => 'Schneider',
                'industry' => 'Elektrikal',
                'logo_path' => '/uploads/clients/6a1306559869b.webp',
                'created_at' => '2026-05-23 07:38:56',
                'updated_at' => '2026-05-24 14:08:21',
            ],
            [
                'id' => '8',
                'name' => 'Mitsubishi',
                'industry' => 'Otomotif & Elektrik',
                'logo_path' => '/uploads/clients/6a1306b77aefe.webp',
                'created_at' => '2026-05-23 07:38:56',
                'updated_at' => '2026-05-24 14:09:59',
            ],
        ]);

        DB::table('certificates')->truncate();
        DB::table('certificates')->insert([
            [
                'id' => '1',
                'name' => 'ISO 9001:2015-TES',
                'desc' => 'Sistem manajemen kualitas untuk konsistensi produk dan kepuasan pelanggan',
                'icon' => 'ti-shield',
                'img' => '/uploads/certificates/6a11b56cd48b4.webp',
                'order' => '1',
                'created_at' => '2026-05-23 14:10:52',
                'updated_at' => '2026-05-24 08:50:40',
            ],
            [
                'id' => '2',
                'name' => 'IATF 16949',
                'desc' => 'Standar kualitas internasional khusus industri otomotif',
                'icon' => 'ti-car',
                'img' => '/uploads/certificates/6a12bbbc433d2.webp',
                'order' => '2',
                'created_at' => '2026-05-23 14:16:52',
                'updated_at' => '2026-05-24 08:50:05',
            ],
            [
                'id' => '3',
                'name' => 'ISO 14001',
                'desc' => 'Sistem manajemen lingkungan untuk operasional yang berkelanjutan',
                'icon' => 'ti-leaf',
                'img' => '/uploads/certificates/6a132abe1d90f.webp',
                'order' => '3',
                'created_at' => '2026-05-23 14:16:52',
                'updated_at' => '2026-05-24 16:43:42',
            ],
            [
                'id' => '4',
                'name' => '5S & Kaizen',
                'desc' => 'Penerapan lean manufacturing untuk efisiensi dan perbaikan berkelanjutan',
                'icon' => 'ti-award',
                'img' => null,
                'order' => '4',
                'created_at' => '2026-05-23 14:16:52',
                'updated_at' => '2026-05-23 14:16:52',
            ],
        ]);

        DB::table('galleries')->truncate();
        DB::table('galleries')->insert([
            [
                'id' => '1',
                'title' => 'TES',
                'category' => 'Operations',
                'description' => 'TES',
                'image_url' => '/uploads/galleries/9pWgpVrUSmgjFY61j9F0m4ADVNwjjTc60XXv0pEo.jpg',
                'display_order' => '1',
                'created_at' => '2026-05-24 10:41:41',
                'updated_at' => '2026-05-24 10:42:20',
            ],
            [
                'id' => '2',
                'title' => 'TES2',
                'category' => 'Operations',
                'description' => 'TESSS',
                'image_url' => '/uploads/galleries/4nqxZiwFPiaTeW0y5saW7rcE7NozRSQUd8sxHlHo.jpg',
                'display_order' => '1',
                'created_at' => '2026-05-24 10:43:41',
                'updated_at' => '2026-05-24 10:43:41',
            ],
            [
                'id' => '3',
                'title' => 'TES233',
                'category' => 'Operations',
                'description' => 'ASDSADAD',
                'image_url' => '/uploads/galleries/2kxfYhgOYSwKlo94Y43PEqxYGtgemK5ofAdq4gC7.jpg',
                'display_order' => '1',
                'created_at' => '2026-05-24 10:43:57',
                'updated_at' => '2026-05-24 10:43:57',
            ],
            [
                'id' => '4',
                'title' => 'ADADA',
                'category' => 'Operations',
                'description' => 'ADASDSA',
                'image_url' => '/uploads/galleries/zHc0emEVYQriItgqgqt6V7Bxv8SHw2Df77BB8YW8.jpg',
                'display_order' => '1',
                'created_at' => '2026-05-24 10:44:09',
                'updated_at' => '2026-05-24 10:44:09',
            ],
            [
                'id' => '5',
                'title' => 'dasdas',
                'category' => 'Team',
                'description' => 'adasdas',
                'image_url' => '/uploads/galleries/OvBRsrQcxERqSKHwZtxaAj9rEdzdjBOs6GRJNVJw.webp',
                'display_order' => '1',
                'created_at' => '2026-05-24 11:17:10',
                'updated_at' => '2026-05-24 11:17:10',
            ],
        ]);

        Schema::enableForeignKeyConstraints();
    }
}
